apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: alessandro.vozza@microsoft.com
    privateKeySecretRef:
      name: letsencrypt-dev
